"""
DebloatKit v1.0 — Themes
Color tokens matching PurgeKit's design language.
Author: Yashwanth Ram Somireddy | TeamExyKings | MIT License
"""

THEMES = {
    "Green": {
        "bg":           "#0a0a0a",
        "bg_card":      "#111111",
        "bg_hover":     "#1a1a1a",
        "accent":       "#00e676",
        "accent_dim":   "#00b359",
        "text":         "#f0f0f0",
        "text_muted":   "#888888",
        "text_dim":     "#555555",
        "border":       "#222222",
        "border_accent":"#00e676",
        "success":      "#00e676",
        "warning":      "#ffab00",
        "error":        "#ff1744",
        "core_red":     "#ff1744",
        "caution":      "#ffab00",
        "safe_green":   "#00e676",
        "keep_gray":    "#555555",
        "locked_red":   "#ff5252",
        "disabled_bg":  "#1a0a0a",
        "tab_selected": "#00e676",
        "progress_bg":  "#1a1a1a",
        "scrollbar":    "#333333",
        "btn_primary":  "#00e676",
        "btn_primary_text": "#0a0a0a",
        "btn_secondary": "#1e1e1e",
        "btn_danger":   "#ff1744",
        "topbar_bg":    "#0d0d0d",
        "log_bg":       "#080808",
        "log_info":     "#888888",
        "log_success":  "#00e676",
        "log_warning":  "#ffab00",
        "log_error":    "#ff1744",
    },
    "Blue": {
        "bg":           "#080c14",
        "bg_card":      "#0e1520",
        "bg_hover":     "#141e2e",
        "accent":       "#2979ff",
        "accent_dim":   "#1a4fd6",
        "text":         "#e8f0ff",
        "text_muted":   "#6b7fa3",
        "text_dim":     "#3d4f6e",
        "border":       "#1a2540",
        "border_accent":"#2979ff",
        "success":      "#00e676",
        "warning":      "#ffab00",
        "error":        "#ff1744",
        "core_red":     "#ff1744",
        "caution":      "#ffab00",
        "safe_green":   "#00e676",
        "keep_gray":    "#3d4f6e",
        "locked_red":   "#ff5252",
        "disabled_bg":  "#14100a",
        "tab_selected": "#2979ff",
        "progress_bg":  "#0e1520",
        "scrollbar":    "#1a2540",
        "btn_primary":  "#2979ff",
        "btn_primary_text": "#ffffff",
        "btn_secondary": "#0e1520",
        "btn_danger":   "#ff1744",
        "topbar_bg":    "#0a1018",
        "log_bg":       "#060a10",
        "log_info":     "#6b7fa3",
        "log_success":  "#00e676",
        "log_warning":  "#ffab00",
        "log_error":    "#ff1744",
    },
    "Purple": {
        "bg":           "#0a080f",
        "bg_card":      "#120e1c",
        "bg_hover":     "#1a1428",
        "accent":       "#d500f9",
        "accent_dim":   "#aa00c8",
        "text":         "#f0e8ff",
        "text_muted":   "#8b7aa8",
        "text_dim":     "#4a3d63",
        "border":       "#1e1430",
        "border_accent":"#d500f9",
        "success":      "#00e676",
        "warning":      "#ffab00",
        "error":        "#ff1744",
        "core_red":     "#ff1744",
        "caution":      "#ffab00",
        "safe_green":   "#00e676",
        "keep_gray":    "#4a3d63",
        "locked_red":   "#ff5252",
        "disabled_bg":  "#0f0a1a",
        "tab_selected": "#d500f9",
        "progress_bg":  "#120e1c",
        "scrollbar":    "#1e1430",
        "btn_primary":  "#d500f9",
        "btn_primary_text": "#ffffff",
        "btn_secondary": "#120e1c",
        "btn_danger":   "#ff1744",
        "topbar_bg":    "#0d0b14",
        "log_bg":       "#080610",
        "log_info":     "#8b7aa8",
        "log_success":  "#00e676",
        "log_warning":  "#ffab00",
        "log_error":    "#ff1744",
    },
    "White": {
        "bg":           "#f5f5f5",
        "bg_card":      "#ffffff",
        "bg_hover":     "#efefef",
        "accent":       "#00897b",
        "accent_dim":   "#00695c",
        "text":         "#1a1a1a",
        "text_muted":   "#666666",
        "text_dim":     "#aaaaaa",
        "border":       "#e0e0e0",
        "border_accent":"#00897b",
        "success":      "#00897b",
        "warning":      "#f57c00",
        "error":        "#d32f2f",
        "core_red":     "#d32f2f",
        "caution":      "#f57c00",
        "safe_green":   "#00897b",
        "keep_gray":    "#999999",
        "locked_red":   "#e53935",
        "disabled_bg":  "#fff3f3",
        "tab_selected": "#00897b",
        "progress_bg":  "#e0e0e0",
        "scrollbar":    "#cccccc",
        "btn_primary":  "#00897b",
        "btn_primary_text": "#ffffff",
        "btn_secondary": "#e8e8e8",
        "btn_danger":   "#d32f2f",
        "topbar_bg":    "#ffffff",
        "log_bg":       "#1a1a1a",
        "log_info":     "#aaaaaa",
        "log_success":  "#00897b",
        "log_warning":  "#f57c00",
        "log_error":    "#d32f2f",
    }
}

RISK_COLORS = {
    "SAFE":        {"Green": "#00e676", "Blue": "#2979ff", "Purple": "#d500f9", "White": "#00897b"},
    "RECOMMENDED": {"Green": "#69ff47", "Blue": "#40c4ff", "Purple": "#ea80fc", "White": "#26a69a"},
    "CAUTION":     {"Green": "#ffab00", "Blue": "#ffab00", "Purple": "#ffab00", "White": "#f57c00"},
    "CORE":        {"Green": "#ff1744", "Blue": "#ff1744", "Purple": "#ff1744", "White": "#d32f2f"},
    "LOCKED":      {"Green": "#ff5252", "Blue": "#ff5252", "Purple": "#ff5252", "White": "#e53935"},
    "KEEP":        {"Green": "#444444", "Blue": "#3d4f6e", "Purple": "#4a3d63", "White": "#aaaaaa"},
}

STATE_COLORS = {
    "enabled":     "#00e676",
    "disabled":    "#ffab00",
    "uninstalled": "#ff5252",
}

def get_theme(name: str) -> dict:
    return THEMES.get(name, THEMES["Green"])

def get_risk_color(risk: str, theme_name: str) -> str:
    return RISK_COLORS.get(risk, RISK_COLORS["SAFE"]).get(theme_name, "#00e676")

def get_state_color(state: str) -> str:
    return STATE_COLORS.get(state, "#888888")

def get_risk_label(risk: str) -> str:
    labels = {
        "SAFE": "✓ Safe",
        "RECOMMENDED": "★ Recommended",
        "CAUTION": "⚠ Caution",
        "CORE": "⛔ Core",
        "LOCKED": "🔒 Locked",
        "KEEP": "— Keep",
    }
    return labels.get(risk, risk)
